name:                dump-type-signatures
version:             0.1.0.0
github:              "AndrewQuinn2020/dump-type-signatures"
license:             BSD3
author:              "Andrew Quinn"
maintainer:          "AndrewQuinn2020@u.northwestern.edu"
copyright:           "2021 Andrew Quinn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AndrewQuinn2020/dump-type-signatures#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  dump-type-signatures-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dump-type-signatures

tests:
  dump-type-signatures-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dump-type-signatures
